# Generated by Django 5.2.3 on 2025-07-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('doctor_id', models.IntegerField(max_length=20)),
                ('age', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
            ],
        ),
    ]
