# Generated by Django 5.2.3 on 2025-07-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doctor_id',
            field=models.IntegerField(),
        ),
    ]
